### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by dnlmzw** [pixijs/html-text#1]
I've tried implementing this, but for some reason it says PIXI is not defined when I import `text-html`

```
ReferenceError: PIXI is not defined
./node_modules/@pixi/text-html/dist/html-text.js
node_modules/@pixi/text-html/dist/html-text.js:8
   5 |  * @pixi/text-html is licensed under the MIT License.
   6 |  * http://www.opensource.org/licenses/mit-license
   7 |  */
>  8 | var _pixi_htmltext=function(t,e,i,o,s,r,n){"use strict";var h=function(t){function e(e,r,n){if(void 0===e&&(e=""),void 0===r&&(r=
```

Here's my import code:

```
import * as PIXI from "pixi.js";
import { HTMLText } from "@pixi/text-html";
```

When loading the library manually, window.PIXI.HTMLText is available as intended:
```
import("pixi.js")
   .then((pixi) => {
      window.PIXI = pixi
      import("@pixi/text-html")
   })
.catch((error) => console.error("Couldn't load PIXI", error));
```

**Comment by bigtimebuddy** [comment]
I think I know what this is. Just to clarify, how are you bundling your code?

**Comment by dnlmzw** [comment]
I'm using PixiJS together with Gatsby / React

**Comment by bigtimebuddy** [comment]
I believe it’s the same issue here: this project is using the browser field incorrectly. 

https://github.com/bigtimebuddy/pixi-svg/issues/10

Gatsby uses webpack which has a similar behavior considering the browser field. The easiest thing is for me to rename this field.

As a temporary workaround: you can set resolve.mainFields to [module, main]. https://webpack.js.org/configuration/resolve/#resolvemainfields

Or manually edit the package.json of the module to change browser field to something like bundle. And rebuild.

Can you verify that either of those fixes the issue? If so, I can make a new release.

**Comment by bigtimebuddy** [comment]
Fixed with 134d552

**Comment by redocecin** [comment]
Hello, did you deploy this fix version to [npm](https://www.npmjs.com/package/@pixi/text-html)? I couldn't find the version v1.0.1 there. It just has only one version v1.0.0. I'm encountering the same problem and I need this fix :(.

**Comment by bigtimebuddy** [comment]
Sorry I must have forgot to publish. Should now be on npm: `@pixi/text-html@1.0.1`

**Comment by redocecin** [comment]
Thanks so much for your quick response. We don't need to update our webpack config now.
