### ISSUE TITLE
flashing between updates

### ISSUE THREAD

**Issue by versole** [pixijs/html-text#18]
When I change css style frequently,  it will flash between updates

version: 2.0.2 (I already have saw the commit "fix flashing between updates", but it seemly still exists

**Comment by bigtimebuddy** [comment]
Please provide a reproduction the issue seems resolved. But maybe you're doing something different?

v2.0.0: https://jsfiddle.net/bigtimebuddy/ftc67o8x/
v2.0.2: https://jsfiddle.net/bigtimebuddy/mdh1to4q/ (fixed)

**Comment by bigtimebuddy** [comment]
Closing, as this is fixed. Please provide an example and I can re-open.
