### ISSUE TITLE
Peer dependencies

### ISSUE THREAD

**Issue by Outfire** [pixijs/html-text#21]
Please, use ">=" instead "^" for module version. It cause to update to latest version of pixi.js modules.
As example after lock pixi.js to 6.3.2 version i will receive type error, because modules in @pixi which needed for html-text are updated to 6.4.2 version.

**Comment by bigtimebuddy** [comment]
I cannot reproduce this:

```
npm install pixi.js@7.0.0
npm install @pixi/text-html
```

Latest pixi.js is 7.0.2, but it's installing 7.0.0 and the peers on this plugin are not installing 7.0.2, as you suggested.

If you're [using yarn](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/), you can specify the resolutions of packages.
