### ISSUE TITLE
Resolution with this.stage.scale

### ISSUE THREAD

**Issue by zero41120** [pixijs/html-text#25]
We have custom logic to detect both browser zoom (`window.devicePixelRatio`) and tool bar that controls (`this.stage.scale`).

When scale event change, we apply resolution as (`scale * devicePixelRatio`), which looks fine with regular Pixi Text, however, this plugin's resolution is not rendered correctly.

**Comment by bigtimebuddy** [comment]
I'm not sure what you mean. Can you please make a reproduction with this:
https://codesandbox.io/s/pixi-html-text-demo-mecjys?file=/src/index.ts

**Comment by zero41120** [comment]
Try this: https://codesandbox.io/s/pixi-html-text-demo-forked-03in2h?file=/src/index.ts

Scale 95%, devicePixelRatio 1.375
![image](https://user-images.githubusercontent.com/10471270/194187202-763a69ac-8d96-4bf9-bec1-73a2d44fbd6d.png)

In our system, it is really noticeable when user is interacting (dragging) the text around the canvas.

**Comment by bigtimebuddy** [comment]
Oh, do you mean that it looks like the html text in that image has a weird line break in the middle?
