### ISSUE TITLE
White screen appears when updating text

### ISSUE THREAD

**Issue by ChasLui** [pixijs/html-text#33]
Currently I use the rich text editor quill.js to generate the html, and then update it to the text part of the HTMLText.
But now I have the problem that when the text is updated the whole HTMLText object will be white screened and then updated to the new content.
The expectation is to update the text without a white screen even if the update is slower.

**Comment by bigtimebuddy** [comment]
Please provide more details, such as browser, and ideally a reproduction.

**Comment by ChasLui** [comment]
> Please provide more details, such as browser, and ideally a reproduction.

Here is a demo site(https://chaslui.github.io/html-text/) where you can quickly enter any content in the Editor and observe that the canvas below will blink.

And demo code in: https://github.com/ChasLui/html-text/tree/pages/docs

**Comment by bigtimebuddy** [comment]
Super helpful demo. Thank you!
