### ISSUE TITLE
About input space

### ISSUE THREAD

**Issue by lykl** [pixijs/html-text#37]
Only one space is displayed when multiple spaces are entered, and the width is not increased if the last character is a space.
Is there any way to enter more than one space?

**Comment by bigtimebuddy** [comment]
Set the `whiteSpace` style property to be `pre`:
https://jsfiddle.net/bigtimebuddy/rauqc2n6/

**Comment by bigtimebuddy** [comment]
whiteSpace works the same as CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
