### ISSUE TITLE
Performance Profile Slow-down in Chrome

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/html-text#38]
Did some benchmarking of `PIXI.HTMLText` vs `PIXI.Text` and found some interesting things:

### 🐢 HTMLText is about 2-4 times slow in Chrome than Text

<img width="678" alt="chrome-1" src="https://user-images.githubusercontent.com/864393/210857940-b6d5cc26-e61a-41e7-8399-d6cda0e22348.png">

### ⚖️  HTMLText is about equal in Safari with Text

<img width="528" alt="safari-1" src="https://user-images.githubusercontent.com/864393/210857984-605db9c5-f7d8-4a55-a6c3-f25bfc812d1c.png">

### 🐇 HTMLText is about 50% faster in Firefox than Text

<img width="624" alt="firefox-1" src="https://user-images.githubusercontent.com/864393/210858140-69bad082-a5cc-4354-9835-251c0584db90.png">

I'm going to profile Chrome to see if we can improve performance. The goal is that this is a non-brainer replacement for Text with no or few concessions.

Example:
https://jsfiddle.net/bigtimebuddy/ntusg3ak/

**Comment by bigtimebuddy** [comment]
Profiled this a little more to wanting to understand why Chrome is so darn slow...

Chrome is 3-4x slower when waiting for onload of a data-uri, for instance `img.src = 'data:image/svg+xml;charset=utf-8,...'` when compared to Firefox or Safari. I'm not sure why. Using alternatives like using a Blob url, didn't work and weren't faster.

**Comment by ChasLui** [comment]
I have tested that the performance advantage of PIXI.HTMLText is more pronounced in all browsers when the content is longer.
In chrome.
- When the content is 5 `hello world!` lengths, i.e. `const content = "Hello world!".repeat(5);` Both are similar.
- When the content is 6 `hello world!` long, i.e. `const content = "Hello world!".repeat(6);` PIXI.HTMLText performs better.

<img width="2539" alt="image" src="https://user-images.githubusercontent.com/10083758/215240759-962868aa-f5c3-4447-8d47-f00d8aab844a.png">

**Comment by ChasLui** [comment]
> I have tested that the performance advantage of PIXI.HTMLText is more pronounced in all browsers when the content is longer. In chrome.
> 
> * When the content is 5 `hello world!` lengths, i.e. `const content = "Hello world!".repeat(5);` is the same as `PIXI.Text`
> * When the content is 6 `hello world!` long, i.e. `const content = "Hello world!".repeat(6);` is superior to `PIXI.Text` when `PIXI.
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/10083758/215240759-962868aa-f5c3-4447-8d47-f00d8aab844a.png">

Example: 
https://jsfiddle.net/ChasLui/h681b93o/1/

**Comment by ChasLui** [comment]
> > I have tested that the performance advantage of PIXI.HTMLText is more pronounced in all browsers when the content is longer. In chrome.
> > 
> > * When the content is 5 `hello world!` lengths, i.e. `const content = "Hello world!".repeat(5);` is the same as `PIXI.Text`
> > * When the content is 6 `hello world!` long, i.e. `const content = "Hello world!".repeat(6);` is superior to `PIXI.Text` when `PIXI.
> > 
> > <img alt="image" width="2000" src="https://user-images.githubusercontent.com/10083758/215240759-962868aa-f5c3-4447-8d47-f00d8aab844a.png">
> 
> Example: https://jsfiddle.net/ChasLui/h681b93o/1/

<img width="448" alt="image" src="https://user-images.githubusercontent.com/10083758/215241008-7b5f0f9a-c09d-4eed-82fe-8e733c720c7e.png">
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/10083758/215241019-4764e5e9-9d8c-4bd1-ae00-dbbecb5fe141.png">

**Comment by bigtimebuddy** [comment]
Very helpful! Thank you.
