### ISSUE TITLE
Support for measuring HTMLText output dimensions

### ISSUE THREAD

**Issue by rubenlg** [pixijs/html-text#4]
For regular Text objects we have `PIXI.TextMetrics.measureText`, which doesn't require creating the `DisplayObject` to know the dimensions of the text. However, that won't work correctly for `HTMLText` because markup is counted as extra characters.

It would be very useful to have something like `measureText` for `HTMLText` so we can have a lightweight way of measuring the size the text would have before rendering the object.

For my particular case, as a workaround I could create a `div` element, add my text as `innerHTML` and then get the `innerText` to pass it to `PIXI.TextMetrics.measureText`. It wouldn't be completely accurate, since markup can make the font slightly larger, or add extra space, but I don't have these issues. However, for the general case, having an accurate helper in the library would be really nice.

**Comment by bigtimebuddy** [comment]
I can see why this would be helpful. It would allow users to do things like text-fitting without paying a render tax. Likely the approach I would take here would be the same as you're doing. Just measure the `<div>`.
