### ISSUE TITLE
Is there a way to make CSS transitions work?

### ISSUE THREAD

**Issue by antonmihaylov** [pixijs/html-text#40]
I tried the obvious solution of simply adding `transition: all 0.2s` to the style, but that doesn't seem to work.
I feel like it's not compatible with the way the text is rendered, but is there a workaround or any other way to add an animated scale-in effect for example?

**Comment by bigtimebuddy** [comment]
The text is rasterized, so no, CSS transitions won't work unfortunately. You can Animate properties in Pixi of the HTMLText object like alpha to fade in or x/y to translate, scale to size, etc.

**Comment by antonmihaylov** [comment]
Thank you for the quick response, that seems like a good alternative
