### ISSUE TITLE
Typings don't work with Pixi v6

### ISSUE THREAD

**Issue by rubenlg** [pixijs/html-text#8]
Typings use the deprecated global PIXI namespace, which was removed in Pixi v6.

**Comment by bigtimebuddy** [comment]
Typings are now bundled with v6, please don't use @types/pixi.js anymore

**Comment by rubenlg** [comment]
`@types/pixi.js` wasn't necessary with v5.3.10 either. I might have made some other mistake in my setup, because I actually can't reproduce the Typescript compiler error in a fresh repo just with `pixi` and `tex-html` installed. 

Sorry for the noise :(
