### ISSUE TITLE
Pixi 6 not supported

### ISSUE THREAD

**Issue by DouglasLapsley** [pixijs/html-text#9]
"pixi.js": "^6.0.4"

`npm install @pixi/text-html` gives the following error:

![image](https://user-images.githubusercontent.com/15831662/127610135-3bfc2264-e15b-45ac-bbca-6af2845e9913.png)

Looks like `@pixi/math@"^5.0.0"` dependency needs to be updated to `@pixi/math@6.0.4`?  Possibly other deps too?

Thanks.  By the way, I just realised that Pixi v6 is in pre-release, so I tried downgrading to that v5 and that just caused other dependencies to fail.

**Comment by bigtimebuddy** [comment]
You're right, I'll work on an update to bump to support v6. Thanks for pointing this out.

**Comment by DouglasLapsley** [comment]
Amazing thank you!
